

on:
  push:
    branches:
      - master # Change to the branch you want CI/CD to trigger on

name: Build and Distribute APK
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build with Gradle
        run: ./gradlew assembleDebug  # Change to assembleRelease if you want the release APK

      - name: List APKs
        run: ls app/build/outputs/apk/debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk-debug
          path: app\build\outputs\apk\debug




