name: Upload APK Artifact

on:
  push:
    branches:
      - main # Change to the branch you want CI/CD to trigger on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Download Dependencies
        run: ./gradlew build

      - name: Build APK
        run: ./gradlew assembleRelease

  uses: actions/upload-artifact@v2
  with:
    name: apk-release
    path: app/build/outputs/apk/release/app-release.apk

