on:
  push:
    branches:
      - dev-testing # Change to the branch you want CI/CD to trigger on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew


      - name: Download Dependencies
        run: ./gradlew build

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/outputs/apk/debug/*"
          tag : v0.0.2
          token : ${{ secrets.TOKEN}}
